name: my_training_app
description: "Test app created by damodarshubh@gmail.com."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_bloc: 8.1.6
  http: 1.2.2
  carousel_slider: 5.0.0
  intl: ^0.20.1
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/trainings_dummy_date.json
    - assets/images/dashboard_assets/

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Bold.otf
          weight: 700
        - asset: fonts/Metropolis-ExtraBold.otf
          weight: 800
        - asset: fonts/Metropolis-Light.otf
          weight: 300
        - asset: fonts/Metropolis-Medium.otf
          weight: 500
        - asset: fonts/Metropolis-Regular.otf
          weight: 400
        - asset: fonts/Metropolis-SemiBold.otf
          weight: 600
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
